sudo: required
services:
  - docker

before_install:
  - docker build -t edvinasstanys/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edvinasstanys/docker-react npm run test -- --coverage